INSERT INTO tbl_todo (id, title, completed) VALUES
    (RANDOM_UUID(), 'Buy groceries', FALSE),
    (RANDOM_UUID(), 'Call mom', FALSE),
    (RANDOM_UUID(), 'Pay rent', TRUE),
    (RANDOM_UUID(), 'Finish report', FALSE),
    (RANDOM_UUID(), 'Book dentist', FALSE),
    (RANDOM_UUID(), 'Clean kitchen', FALSE),
    (RANDOM_UUID(), 'Send invoice', TRUE),
    (RANDOM_UUID(), 'Update CV', TRUE),
    (RANDOM_UUID(), 'Car wash', TRUE),
    (RANDOM_UUID(), 'Gym workout', TRUE),
    (RANDOM_UUID(), 'Plan trip', TRUE),
    (RANDOM_UUID(), 'Team meeting', TRUE),
    (RANDOM_UUID(), 'Fix bike', FALSE),
    (RANDOM_UUID(), 'Water plants', FALSE),
    (RANDOM_UUID(), 'Backup laptop', TRUE),
    (RANDOM_UUID(), 'Read article', FALSE),
    (RANDOM_UUID(), 'Buy birthday gift', TRUE),
    (RANDOM_UUID(), 'Check emails', TRUE),
    (RANDOM_UUID(), 'Walk dog', FALSE),
    (RANDOM_UUID(), 'Order printer ink', TRUE),
    (RANDOM_UUID(), 'Review code', FALSE),
    (RANDOM_UUID(), 'Schedule haircut', FALSE),
    (RANDOM_UUID(), 'Prepare slides', TRUE),
    (RANDOM_UUID(), 'Call insurance', TRUE),
    (RANDOM_UUID(), 'Clean inbox', FALSE);
