openapi: 3.0.3
info:
  title: Todo API
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /todos:
    get:
      operationId: listTodos
      summary: List todos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items: { $ref: '#/components/schemas/Todo' }
    post:
      operationId: createTodo
      summary: Create todo
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/TodoCreate' }
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Todo' }
  /todos/{id}:
    get:
      operationId: getTodo
      summary: Get todo
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string, format: uuid }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Todo' }
        '404':
          description: Not Found
components:
  schemas:
    Todo:
      type: object
      required: [id, title, done]
      properties:
        id:    { type: string, format: uuid }
        title: { type: string, minLength: 1 }
        done:  { type: boolean }
    TodoCreate:
      type: object
      required: [title]
      properties:
        title: { type: string, minLength: 1 }
