name: Java Tests

on:
  push:
    branches:
      - main
      - 'feature/**'
    paths:
      - 'src/**'
      - 'pom.xml'
  pull_request:
    branches:
      - main
      - 'feature/**'
    paths:
      - 'src/**'
      - 'pom.xml'

permissions:
  contents: read
  checks: write
  pull-requests: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and Test (Unit, Integration)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build and run tests
        run: |
          mvn -B -U -e verify
        env:
          MAVEN_OPTS: -Xmx1g

      - name: Publish JUnit test report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            **/target/surefire-reports/TEST-*.xml

      - name: Upload surefire reports as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: surefire-reports
          path: |
            **/target/surefire-reports/**
          if-no-files-found: warn
